[package]
name = "cumulus-service"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
# Cumulus dependencies
cumulus-consensus = { path = "../consensus" }
cumulus-collator = { path = "../collator" }
cumulus-primitives = { path = "../primitives" }
cumulus-network = { path = "../network" }

# Substrate dependencies
sc-service = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-client-api = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-consensus = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-runtime = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-api = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-core = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-inherents = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-blockchain = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }

# Polkadot dependencies
polkadot-collator = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }
polkadot-primitives = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }
polkadot-service = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }
# TODO should be dev dependency
polkadot-test-service = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }

[dev-dependencies]
