[package]
name = 'rococo-collator'
version = '0.1.0'
authors = ["Parity Technologies <admin@parity.io>"]
build = 'build.rs'
edition = '2018'

[[bin]]
name = 'rococo-collator'
path = 'src/main.rs'

[dependencies]
derive_more = '0.15.0'
exit-future = '0.1.4'
futures = { version = "0.3.1", features = ["compat"] }
log = '0.4.8'
parking_lot = '0.9.0'
trie-root = '0.15.2'
codec = { package = 'parity-scale-codec', version = '1.0.0' }
structopt = "0.3.3"
ansi_term = "0.12.1"
serde = { version = "1.0.101", features = ["derive"] }
hex-literal = "0.2.1"

# Parachain dependencies
parachain-runtime = { package = "cumulus-test-parachain-runtime", path = "runtime" }
parachain-contracts-runtime = { package = "cumulus-contracts-parachain-runtime", path = "contracts-runtime" }
rococo-parachain-primitives = { path = "primitives" }

# Substrate dependencies
sp-runtime = { git = "file:///home/cecile/repos/substrate", default-features = false, branch = "rococo-branch" }
sp-io = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-core = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-inherents = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-consensus = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-session = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-consensus = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-cli = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-client-api = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-executor = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-service = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-transaction-pool = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-transaction-pool = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-network = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-basic-authorship = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch", version = "0.8.0-rc5" }
sp-timestamp = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-blockchain = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-block-builder = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-trie = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-api = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-finality-grandpa = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-informant = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-chain-spec = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sc-rpc = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
sp-offchain = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }

# RPC related dependencies
cumulus-pallet-contracts-rpc = { path = "./pallets/contracts/rpc" }
jsonrpc-core = "14.2.0"

# Cumulus dependencies
cumulus-consensus = { path = "../consensus" }
cumulus-collator = { path = "../collator" }
cumulus-network = { path = "../network" }
cumulus-primitives = { path = "../primitives" }
cumulus-service = { path = "../service" }

# Polkadot dependencies
polkadot-primitives = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }
polkadot-collator = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }
polkadot-service = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }
polkadot-cli = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }
polkadot-test-service = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }
polkadot-parachain = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }

[build-dependencies]
substrate-build-script-utils = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }

[dev-dependencies]
assert_cmd = "0.12"
nix = "0.17"
rand = "0.7.3"
tokio = { version = "0.2.13", features = ["macros"] }

# Polkadot dependencies
polkadot-runtime-common = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }
polkadot-test-runtime = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }
polkadot-test-runtime-client = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }
polkadot-test-service = { git = "file:///home/cecile/repos/polkadot", branch = "rococo-branch" }

# Substrate dependencies
pallet-sudo = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
substrate-test-client = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
substrate-test-runtime-client = { git = "file:///home/cecile/repos/substrate", branch = "rococo-branch" }
